name: "Build nextsec image"

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'master'
    paths:
      - 'config/**'
      - 'files/**'
      - 'packages/**'
  pull_request:
    paths:
      - 'config/**'
      - 'files/**'

jobs:
  publish_images:
    name: 'Build nextsec image'
    runs-on: self-hosted
    env:
      IMAGETAG: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v2
      - id: build
        run: |
          # Build the image
          ./run
      - uses: actions/upload-artifact@v3
        with:
          name: core_packages
          path: bin/targets/**/packages/**
      - uses: actions/upload-artifact@v3
        with:
          name: packages
          path: bin/packages/**/**
      - uses: actions/upload-artifact@v3
        with:
          name: ext4-image
          path: bin/targets/**/nextsecurity-*-x86-64-generic-ext4-combined.img.gz
      - uses: actions/upload-artifact@v3
        with:
          name: squashfs-image
          path: bin/targets/**/nextsecurity-*-x86-64-generic-squashfs-combined.img.gz
