name: "Build NextSecurity image"

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'config/**'
      - 'files/**'
      - 'packages/**'
      - 'patches/**'
  pull_request:
    paths:
      - 'config/**'
      - 'files/**'
      - 'packages/**'
      - 'patches/**'

jobs:
  publish_images:
    name: 'Build NextSecurity image'
    runs-on: self-hosted
    env:
      IMAGETAG: ${{ github.ref_name }}
      DO_SPACE_NAME: 'distfeed-nextsecurity'
      DO_SPACE_REGION: 'fra1'
      CDN_NAME: 'distfeed.nethserver.org'
      USIGN_PUB_KEY: ${{ secrets.USIGN_PUB_KEY }}
      USIGN_PRIV_KEY: ${{ secrets.USIGN_PRIV_KEY }}
      NETIFYD_ACCESS_TOKEN: ${{ secrets.NETIFYD_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - id: build
        name: Build the image
        run: |
          # Build the image
          ./run
      - id: release
        name: Update latest_release file
        run: |
          # Setup OWRT_VERSION env variable for release action
          grep '^OWRT_VERSION' builder/build-builder | tr -d '"' >> $GITHUB_ENV
          # Create release file pointing to OWRT_VERSION
          grep '^OWRT_VERSION' builder/build-builder | tr -d '"' | cut -d'=' -f2 > latest_release
      - uses: actions/upload-artifact@v3
        name: Publish images as temporary artifacts
        with:
          name: ext4-x86_64-image
          path: bin/targets/x86/64/nextsecurity-*-x86-64-generic-ext4-combined-efi.img.gz
      - uses: BetaHuhn/do-spaces-action@v2
        name: Publish packages to distfeed repository
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          access_key: ${{ secrets.DO_SPACE_ACCESS_KEY }}
          secret_key: ${{ secrets.DO_SPACE_SECRET_KEY }}
          space_name: ${{ env.DO_SPACE_NAME }}
          space_region: ${{ env.DO_SPACE_REGION }}
          cdn_domain: ${{ env.CDN_DOMAIN }}
          source: bin/packages
          out_dir: ${{ env.OWRT_VERSION }}/packages
      - uses: BetaHuhn/do-spaces-action@v2
        name: Publish images to distfeed repository
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          access_key: ${{ secrets.DO_SPACE_ACCESS_KEY }}
          secret_key: ${{ secrets.DO_SPACE_SECRET_KEY }}
          space_name: ${{ env.DO_SPACE_NAME }}
          space_region: ${{ env.DO_SPACE_REGION }}
          cdn_domain: ${{ env.CDN_DOMAIN }}
          source: bin/targets
          out_dir: ${{ env.OWRT_VERSION }}/targets
      - uses: BetaHuhn/do-spaces-action@v2
        name: Publish latest_release to distfeed repository
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          access_key: ${{ secrets.DO_SPACE_ACCESS_KEY }}
          secret_key: ${{ secrets.DO_SPACE_SECRET_KEY }}
          space_name: ${{ env.DO_SPACE_NAME }}
          space_region: ${{ env.DO_SPACE_REGION }}
          cdn_domain: ${{ env.CDN_DOMAIN }}
          source: latest_release
