name: "Build NethSecurity image"

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'config/**'
      - 'files/**'
      - 'packages/**'
      - 'patches/**'
  pull_request:
    paths:
      - 'config/**'
      - 'files/**'
      - 'packages/**'
      - 'patches/**'

jobs:
  publish_images:
    name: 'Build NethSecurity image'
    runs-on: self-hosted
    env:
      IMAGETAG: ${{ github.ref_name }}
      DO_SPACE_NAME: 'nethsecurity'
      DO_SPACE_REGION: 'ams3'
      CDN_NAME: 'updates.nethsecurity.nethserver.org'
      USIGN_PUB_KEY: ${{ secrets.USIGN_PUB_KEY }}
      USIGN_PRIV_KEY: ${{ secrets.USIGN_PRIV_KEY }}
      NETIFYD_ACCESS_TOKEN: ${{ secrets.NETIFYD_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - id: build
        name: Build the image
        run: |
          # Build the image
          # The run script will set VERSION, REPO_CHANNEL, and OWRT_VERSION env variables
          ./run
      - id: release
        name: Update latest_release file
        run: |
          # Create release file pointing to VERSION
          echo ${{ env.VERSION }} > latest_release
      - uses: actions/upload-artifact@v3
        name: Publish images as temporary artifacts
        with:
          name: x86_64-image
          path: bin/targets/x86/64/nethsecurity-*-x86-64-generic-*-combined-efi.img.gz
      - uses: BetaHuhn/do-spaces-action@v2
        name: Publish packages inside the rolling repository
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          access_key: ${{ secrets.DO_SPACE_ACCESS_KEY }}
          secret_key: ${{ secrets.DO_SPACE_SECRET_KEY }}
          space_name: ${{ env.DO_SPACE_NAME }}
          space_region: ${{ env.DO_SPACE_REGION }}
          cdn_domain: ${{ env.CDN_DOMAIN }}
          source: bin/packages
          out_dir: ${{ env.REPO_CHANNEL }}/${{ env.OWRT_VERSION }}/packages
      - uses: BetaHuhn/do-spaces-action@v2
        name: Publish packages inside the fixed repository
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          access_key: ${{ secrets.DO_SPACE_ACCESS_KEY }}
          secret_key: ${{ secrets.DO_SPACE_SECRET_KEY }}
          space_name: ${{ env.DO_SPACE_NAME }}
          space_region: ${{ env.DO_SPACE_REGION }}
          cdn_domain: ${{ env.CDN_DOMAIN }}
          source: bin/packages
          out_dir: ${{ env.REPO_CHANNEL }}/${{ env.VERSION }}/packages
      - uses: BetaHuhn/do-spaces-action@v2
        name: Publish images insde the fixed repository
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          access_key: ${{ secrets.DO_SPACE_ACCESS_KEY }}
          secret_key: ${{ secrets.DO_SPACE_SECRET_KEY }}
          space_name: ${{ env.DO_SPACE_NAME }}
          space_region: ${{ env.DO_SPACE_REGION }}
          cdn_domain: ${{ env.CDN_DOMAIN }}
          source: bin/targets
          out_dir: ${{ env.REPO_CHANNEL }}/${{ env.VERSION }}/packages
      - uses: BetaHuhn/do-spaces-action@v2
        name: Publish latest_release inside the repository
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          access_key: ${{ secrets.DO_SPACE_ACCESS_KEY }}
          secret_key: ${{ secrets.DO_SPACE_SECRET_KEY }}
          space_name: ${{ env.DO_SPACE_NAME }}
          space_region: ${{ env.DO_SPACE_REGION }}
          cdn_domain: ${{ env.CDN_DOMAIN }}
          source: latest_release
          out_dir: ${{ env.REPO_CHANNEL }}/
